"""
generate_voice_pack.py
─────────────────────────────────────────────────────────
สร้างไฟล์ thai_voice_pack.js ที่บรรจุเสียงภาษาไทยแบบ base64
สำหรับใช้ใน q.html บน Smart TV ที่ไม่สามารถใช้ TTS จาก network

วิธีใช้:
    pip install edge-tts
    python generate_voice_pack.py --max 99 --rooms "ห้องตรวจ 1" "ห้องตรวจ 2"

จะได้ไฟล์ thai_voice_pack.js (~500KB–1MB) นำไปวางในโฟลเดอร์เดียวกับ q.html
─────────────────────────────────────────────────────────
"""

import asyncio
import base64
import json
import argparse
import os
import sys

try:
    import edge_tts
except ImportError:
    print("ERROR: ต้องติดตั้ง edge-tts ก่อน")
    print("    pip install edge-tts")
    sys.exit(1)


# ─── เสียงไทยที่ใช้ ───
# th-TH-PremwadeeNeural — เสียงผู้หญิง (แนะนำ)
# th-TH-NiwatNeural     — เสียงผู้ชาย
DEFAULT_VOICE = "th-TH-PremwadeeNeural"


# ─── ตัวเลขไทย ───
THAI_DIGITS = ['ศูนย์','หนึ่ง','สอง','สาม','สี่','ห้า','หก','เจ็ด','แปด','เก้า']


def thai_number(n):
    if n == 0: return THAI_DIGITS[0]
    if n < 10: return THAI_DIGITS[n]
    if n == 10: return 'สิบ'
    if n < 20:
        return 'สิบเอ็ด' if n == 11 else 'สิบ' + THAI_DIGITS[n - 10]
    if n < 100:
        t, o = n // 10, n % 10
        tens = 'ยี่สิบ' if t == 2 else THAI_DIGITS[t] + 'สิบ'
        if o == 0: return tens
        if o == 1: return tens + 'เอ็ด'
        return tens + THAI_DIGITS[o]
    if n < 1000:
        h, r = n // 100, n % 100
        return THAI_DIGITS[h] + 'ร้อย' + ('' if r == 0 else thai_number(r))
    return ' '.join(THAI_DIGITS[int(c)] for c in str(n))


# ─── ประโยคคงที่ ───
PHRASES = {
    'intro': 'ขอเชิญคิวหมายเลข',
    'enter': 'เข้า',
    'to_room': 'เข้าห้องตรวจหมายเลข',
}


async def gen_audio(text, voice):
    """สร้าง MP3 จากข้อความด้วย Edge TTS — return bytes"""
    communicate = edge_tts.Communicate(text, voice)
    audio_bytes = b''
    async for chunk in communicate.stream():
        if chunk['type'] == 'audio':
            audio_bytes += chunk['data']
    return audio_bytes


async def main():
    parser = argparse.ArgumentParser(description='Generate Thai voice pack')
    parser.add_argument('--max', type=int, default=99,
                        help='จำนวนคิวสูงสุด (default 99) — เพิ่มถ้าคลินิกใหญ่')
    parser.add_argument('--voice', default=DEFAULT_VOICE,
                        help=f'ชื่อเสียง (default {DEFAULT_VOICE})')
    parser.add_argument('--rooms', nargs='*', default=[],
                        help='ชื่อห้องตรวจตามที่ตั้งใน q-setting.html')
    parser.add_argument('--output', default='thai_voice_pack.js')
    args = parser.parse_args()

    print(f'─────────────────────────────────────────')
    print(f'Voice : {args.voice}')
    print(f'Max # : {args.max}')
    print(f'Rooms : {len(args.rooms)} room(s)')
    print(f'─────────────────────────────────────────')

    segments = {}
    rooms_audio = {}

    # 1) ประโยคคงที่
    for key, text in PHRASES.items():
        print(f'  [phrase] {key}: "{text}"')
        audio = await gen_audio(text, args.voice)
        segments[key] = base64.b64encode(audio).decode()

    # 2) ตัวเลข 0..max
    for n in range(0, args.max + 1):
        thai = thai_number(n)
        if n % 20 == 0 or n == args.max:
            print(f'  [number] n{n}: "{thai}"')
        audio = await gen_audio(thai, args.voice)
        segments[f'n{n}'] = base64.b64encode(audio).decode()

    # 3) ชื่อห้องตรวจ (ถ้าผู้ใช้ระบุ)
    for room in args.rooms:
        print(f'  [room]   "{room}"')
        audio = await gen_audio(room, args.voice)
        rooms_audio[room] = base64.b64encode(audio).decode()

    # 4) เขียนไฟล์ JS
    js_content = (
        '// Thai Voice Pack — generated by generate_voice_pack.py\n'
        f'// Voice: {args.voice}\n'
        f'// Numbers: 0..{args.max}\n'
        f'// Rooms: {len(args.rooms)}\n'
        'window.THAI_VOICE_PACK = '
        + json.dumps({
            'voice': args.voice,
            'max': args.max,
            'segments': segments,
            'rooms': rooms_audio
        }, ensure_ascii=False)
        + ';\n'
    )

    with open(args.output, 'w', encoding='utf-8') as f:
        f.write(js_content)

    size_kb = os.path.getsize(args.output) // 1024
    print(f'─────────────────────────────────────────')
    print(f'✓ สำเร็จ! {args.output} ({size_kb} KB)')
    print(f'  ทั้งหมด {len(segments)} segments + {len(rooms_audio)} rooms')
    print()
    print('ขั้นตอนถัดไป:')
    print(f'  1) วางไฟล์ {args.output} ในโฟลเดอร์เดียวกับ q.html')
    print('  2) เปิด q.html บน TV — voice pack จะถูกใช้อัตโนมัติ')


if __name__ == '__main__':
    asyncio.run(main())
